name: Rust

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory
    branches:
    - master # Only trigger on the development branch

env:
  CARGO_TERM_COLOR: always

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Run test
      - run: cargo test

      - name: Build wasm
      - run:  wasm-pack build --out-dir "./www/pkg" --target web 

      - name: Perform Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./koweb/www
